server:
  host: localhost
  port: 3000
  cors:
    - 'http://localhost:4200'
swagger:
  title: Server
  description: The API description
  version: 1.0
  tag:
  path: documentation
mongodb:
  uri: mongodb://localhost:27017/tadaweb
